# Generated by Django 2.2.3 on 2019-07-31 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('amount_items', models.IntegerField(blank=True, default=0, null=True)),
                ('amount_inner_categories', models.IntegerField(blank=True, default=0, null=True)),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nested_category', to='shop.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('owner', models.CharField(blank=True, max_length=255)),
                ('price', models.FloatField()),
                ('description', models.TextField(blank=True, max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('amount_views', models.IntegerField(blank=True, default=None, null=True)),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.Category')),
            ],
        ),
    ]
