# Generated by Django 2.2.3 on 2019-08-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190731_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='amount_inner_categories',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
