# Generated by Django 2.2.3 on 2019-08-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20190801_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='amount_items',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
