# Generated by Django 2.2.3 on 2019-08-01 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190801_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='child',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nested_category', to='shop.Category'),
        ),
    ]
